"""Tables-1.103

Revision ID: 05dffa1a395b
Revises: 8283c1c2f514
Create Date: 2026-07-24 15:37:42.363458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05dffa1a395b'
down_revision: Union[str, Sequence[str], None] = '8283c1c2f514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('improvement', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('tasks', 'task_type',
               existing_type=sa.VARCHAR(),
            #    type_=sa.Enum('PERMANENT', 'DAILY', 'WEEKLY', name='tasktype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_type',
               existing_type=sa.Enum('PERMANENT', 'DAILY', 'WEEKLY', name='tasktype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('equipment')
    # ### end Alembic commands ###
