"""Tables-1.104

Revision ID: 0fb687ab3d3f
Revises: 05dffa1a395b
Create Date: 2026-07-24 16:31:07.140831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb687ab3d3f'
down_revision: Union[str, Sequence[str], None] = '05dffa1a395b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('equipment_user_id_key'), 'equipment', type_='unique')
    op.alter_column('tasks', 'task_type',
               existing_type=sa.VARCHAR(),
            #    type_=sa.Enum('PERMANENT', 'DAILY', 'WEEKLY', name='tasktype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_type',
            #    existing_type=sa.Enum('PERMANENT', 'DAILY', 'WEEKLY', name='tasktype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('equipment_user_id_key'), 'equipment', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
