"""Tables-1.11.1

Revision ID: 23d0cb3c9d51
Revises: b007ce6056eb
Create Date: 2026-04-30 22:47:47.778080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d0cb3c9d51'
down_revision: Union[str, Sequence[str], None] = 'b007ce6056eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('step', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tasks', 'step')
    # ### end Alembic commands ###
