"""Tables-1.11

Revision ID: b007ce6056eb
Revises: 04622b3dd715
Create Date: 2026-04-30 22:24:57.145462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b007ce6056eb'
down_revision: Union[str, Sequence[str], None] = '04622b3dd715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('user_tasks', sa.Column('reward_claimed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tasks', 'reward_claimed')
    op.drop_column('user_tasks', 'completed')
    # ### end Alembic commands ###
